# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from algorithms import *
import os


class Ui_MainForm(object):
    def setupUi(self, MainForm):
        MainForm.setObjectName("MainForm")
        MainForm.setWindowModality(QtCore.Qt.WindowModality.NonModal)
        MainForm.resize(964, 780)

        #Relative path to icons
        file_path = os.path.abspath(os.path.dirname(__file__)) # gets the path to working directory

        self.centralwidget = QtWidgets.QWidget(parent=MainForm)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Canvas = Draw(parent=self.centralwidget)
        self.Canvas.setObjectName("Canvas")
        self.horizontalLayout.addWidget(self.Canvas)
        MainForm.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainForm)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 964, 31))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSimplify = QtWidgets.QMenu(parent=self.menubar)
        self.menuSimplify.setObjectName("menuSimplify")
        self.menuCompute = QtWidgets.QMenu(parent=self.menubar)
        self.menuCompute.setObjectName("menuCompute")
        self.menuClear = QtWidgets.QMenu(parent=self.menubar)
        self.menuClear.setObjectName("menuClear")
        MainForm.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainForm)
        self.statusbar.setObjectName("statusbar")
        MainForm.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(parent=MainForm)
        self.toolBar.setObjectName("toolBar")
        MainForm.addToolBar(QtCore.Qt.ToolBarArea.TopToolBarArea, self.toolBar)
        self.actionOpen = QtGui.QAction(parent=MainForm)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(f"{file_path}/icons/open_file.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionOpen.setIcon(icon)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtGui.QAction(parent=MainForm)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(f"{file_path}/icons/exit.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionExit.setIcon(icon1)
        self.actionExit.setObjectName("actionExit")
        self.actionEuclidean_distance = QtGui.QAction(parent=MainForm)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(f"{file_path}/icons/eucl_distance.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionEuclidean_distance.setIcon(icon2)
        self.actionEuclidean_distance.setObjectName("actionEuclidean_distance")
        self.actionReumann_Witkam = QtGui.QAction(parent=MainForm)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(f"{file_path}/icons/witkamm.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionReumann_Witkam.setIcon(icon3)
        self.actionReumann_Witkam.setObjectName("actionReumann_Witkam")
        self.actionDouglas_Peucker = QtGui.QAction(parent=MainForm)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(f"{file_path}/icons/douglas_peucker.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionDouglas_Peucker.setIcon(icon4)
        self.actionDouglas_Peucker.setObjectName("actionDouglas_Peucker")
        self.actionWhyatt = QtGui.QAction(parent=MainForm)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(f"{file_path}/icons/whyatt.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionWhyatt.setIcon(icon5)
        self.actionWhyatt.setObjectName("actionWhyatt")
        self.actionArrea_displacement = QtGui.QAction(parent=MainForm)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(f"{file_path}/icons/area_displ.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionArrea_displacement.setIcon(icon6)
        self.actionArrea_displacement.setObjectName("actionArrea_displacement")
        self.actionLLR = QtGui.QAction(parent=MainForm)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(f"{file_path}/icons/llr.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionLLR.setIcon(icon7)
        self.actionLLR.setObjectName("actionLLR")
        self.actionClear_results = QtGui.QAction(parent=MainForm)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(f"{file_path}/icons/clear.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionClear_results.setIcon(icon8)
        self.actionClear_results.setObjectName("actionClear_results")
        self.actionClear_All = QtGui.QAction(parent=MainForm)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(f"{file_path}/icons/clear_all.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionClear_All.setIcon(icon9)
        self.actionClear_All.setObjectName("actionClear_All")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuSimplify.addAction(self.actionEuclidean_distance)
        self.menuSimplify.addAction(self.actionReumann_Witkam)
        self.menuSimplify.addAction(self.actionDouglas_Peucker)
        self.menuSimplify.addAction(self.actionWhyatt)
        self.menuCompute.addAction(self.actionArrea_displacement)
        self.menuCompute.addAction(self.actionLLR)
        self.menuClear.addAction(self.actionClear_results)
        self.menuClear.addAction(self.actionClear_All)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSimplify.menuAction())
        self.menubar.addAction(self.menuCompute.menuAction())
        self.menubar.addAction(self.menuClear.menuAction())
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionEuclidean_distance)
        self.toolBar.addAction(self.actionReumann_Witkam)
        self.toolBar.addAction(self.actionDouglas_Peucker)
        self.toolBar.addAction(self.actionWhyatt)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionArrea_displacement)
        self.toolBar.addAction(self.actionLLR)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionClear_results)
        self.toolBar.addAction(self.actionClear_All)
        self.toolBar.addSeparator()
        
        #User-defined connections
        self.actionDouglas_Peucker.triggered.connect(self.simplifyDouglasPeuckerClick)
        self.actionEuclidean_distance.triggered.connect(self.simplifyEuclideanDistanceClick)
        self.actionWhyatt.triggered.connect(self.simplifyWhyattClick)
        self.actionLLR.triggered.connect(self.LLRClick)
        self.actionArrea_displacement.triggered.connect(self.AreaDisplacementClick)
        self.actionClear_All.triggered.connect(self.clearAllClick)
        self.actionClear_results.triggered.connect(self.clearResultClick)

        self.retranslateUi(MainForm)
        QtCore.QMetaObject.connectSlotsByName(MainForm)
        
        
    #User defined functions
    def clearAllClick(self):
        #Clears entire canvas
        self.Canvas.clearCanvas()


    def clearResultClick(self):
        #Clears result polylines
        self.Canvas.clearResult()


    def simplifyDouglasPeuckerClick(self):
        
        #Get source polyline
        polyline = self.Canvas.getPolyline()

        #Create algorithms instance
        a = Algorithms()
        
        #Call D-P
        polyline_simp = a.simplifyDouglasPeucker(polyline, 30)

        #Set results
        self.Canvas.setPolylineSimp(polyline_simp)
        
        #Repaint
        self.Canvas.repaint()
        
        
    def simplifyEuclideanDistanceClick(self):
        #Get source polyline
        polyline = self.Canvas.getPolyline()

        #Create algorithms instance
        a = Algorithms()
        
        #Call euclidean distance
        polyline_simp = a.simplifyEuclideanDistance(polyline, 100)

        #Set results
        self.Canvas.setPolylineSimp(polyline_simp)
        
        #Repaint
        self.Canvas.repaint()


    def simplifyWhyattClick(self):
        #Get source polyline
        polyline = self.Canvas.getPolyline()

        #Create algorithms instance
        a = Algorithms()
        
        #Call euclidean distance
        polyline_simp = a.simplifyWhyatt(polyline, 30)

        #Set results
        self.Canvas.setPolylineSimp(polyline_simp)
        
        #Repaint
        self.Canvas.repaint()


    def LLRClick(self):
        #Get source polyline simp
        polyline_simp = self.Canvas.getPolylineSimp()

        #Create algorithms instance
        a = Algorithms()
        
        #Compute LLR
        llr_result = a.computeLLR(polyline_simp)

        #Create messagebox
        qmb = QMessageBox()
        qmb.setWindowTitle("LLR criterion")
        qmb.setText(str(llr_result))
        
        #Show LLR
        qmb.exec()


    def AreaDisplacementClick(self):
        #Get source polyline and polyline simp
        polyline = self.Canvas.getPolyline()
        polyline_simp = self.Canvas.getPolylineSimp()

        #Create algorithms instance
        a = Algorithms()
        
        #Call Area displacement
        ad_result = a.computeAreaDisplacement(polyline_simp, polyline)

        #Create messagebox
        qmb = QMessageBox()
        qmb.setWindowTitle("Area displacement criterion")
        qmb.setText(str(ad_result))
        
        #Show Area displacement
        qmb.exec()


    def retranslateUi(self, MainForm):
        _translate = QtCore.QCoreApplication.translate
        MainForm.setWindowTitle(_translate("MainForm", "MainWindow"))
        self.menuFile.setTitle(_translate("MainForm", "File"))
        self.menuSimplify.setTitle(_translate("MainForm", "Simplify"))
        self.menuCompute.setTitle(_translate("MainForm", "Compute"))
        self.menuClear.setTitle(_translate("MainForm", "Clear"))
        self.toolBar.setWindowTitle(_translate("MainForm", "toolBar"))
        self.actionOpen.setText(_translate("MainForm", "Open"))
        self.actionOpen.setToolTip(_translate("MainForm", "Open file"))
        self.actionExit.setText(_translate("MainForm", "Exit"))
        self.actionExit.setToolTip(_translate("MainForm", "Exit ap;lication"))
        self.actionEuclidean_distance.setText(_translate("MainForm", "Euclidean distance"))
        self.actionEuclidean_distance.setToolTip(_translate("MainForm", "Simplify polyline using Euclidean distance"))
        self.actionReumann_Witkam.setText(_translate("MainForm", "Reumann-Witkam"))
        self.actionReumann_Witkam.setToolTip(_translate("MainForm", "Simplify polyline using Reumann-Witkam"))
        self.actionDouglas_Peucker.setText(_translate("MainForm", "Douglas-Peucker"))
        self.actionDouglas_Peucker.setToolTip(_translate("MainForm", "Simplify polyline using Douglas-Peucker"))
        self.actionWhyatt.setText(_translate("MainForm", "Whyatt"))
        self.actionWhyatt.setToolTip(_translate("MainForm", "Simplify polyline using Whyatt algorithm"))
        self.actionArrea_displacement.setText(_translate("MainForm", "Area displacement"))
        self.actionArrea_displacement.setToolTip(_translate("MainForm", "Compute area displacement"))
        self.actionLLR.setText(_translate("MainForm", "LLR"))
        self.actionLLR.setToolTip(_translate("MainForm", "Compute local length ratio"))
        self.actionClear_results.setText(_translate("MainForm", "Clear results"))
        self.actionClear_All.setText(_translate("MainForm", "Clear All"))
from draw import Draw


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainForm = QtWidgets.QMainWindow()
    ui = Ui_MainForm()
    ui.setupUi(MainForm)
    MainForm.show()
    sys.exit(app.exec())
